attach(USACrime)
install.packages("VIM")
library(VIM)
aggr(USACrime, prop = FALSE, combined = TRUE, numbers = TRUE, srtVars = TRUE, sortCombs = TRUE, cex.axis = .7,  oma = c(8,5,5,2))

USACrime$medIncomeNA <- ifelse(is.na(medIncome), "Missing", "Not missing")
USACrime$pctEmployNA <- ifelse(is.na(pctEmploy), "Missing", "Not missing")

barplot(prop.table(table(medIncomeNA)), col = c("red", "light blue"), main = "Missing medIncome values")
mosaicplot(table(State, medIncomeNA), cex.axis = .4, col = c("red", "light blue"), main = "Missing medIncome values")
mosaicplot(table(region, medIncomeNA), col = c("red", "light blue"), main = "Missing medIncome values")


par1<- par(mfrow=c(3,3), mar =c(3,3,3,3))
boxplot(pctUrban~medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=.7)
mtext(text = "pctUrban", side =2, line =2, cex =  .7)
boxplot(pctWdiv ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctWdiv", side =2, line =2, cex =  0.7)
boxplot(pctLowEdu ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctLowEdu", side =2, line =2, cex =  0.7)
boxplot(pctNotHSgrad ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctNotHSgrad", side =2, line =2, cex =  0.7)
boxplot(pctCollGrad ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctCollGrad", side =2, line =2, cex =  0.7)
boxplot(pctUnemploy ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctUnemploy", side =2, line =2, cex =  0.7)
boxplot(pctEmploy ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctEmploy", side =2, line =2, cex =  0.7)
boxplot(pctKids2Par ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctKids2Par", side =2, line =2, cex =  0.7)
boxplot(pctKidsBornNevrMarr ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctKidsBornNevrMarr", side =2, line =2, cex =  0.7)
par(par1)

par2<- par(mfrow=c(3,3), mar =c(3,3,3,3))
boxplot(pctHousOccup ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctHouseOccup", side =2, line =2, cex =  0.7)
boxplot(pctHousOwnerOccup ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctHouseOwnerOccup", side =2, line =2, cex =  0.7)
boxplot(pctVacantBoarded ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctVacantBoarded", side =2, line =2, cex =  0.7)
boxplot(pctVacant6up ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.6)
mtext(text = "pctVacant6up", side =2, line =2, cex =  0.6)
boxplot(ownHousMed ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "ownHousMed", side =2, line =2, cex =  0.7)
boxplot(ownHousQrange ~ medIncomeNA, col=c("red", "light blue"))
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "ownHousQrange", side =2, line =2, cex =  0.7)
boxplot(rentMed ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "rentMed", side =2, line =2, cex =  0.7)
boxplot(rentQrange ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "rentQrange", side =2, line =2, cex =  0.7)
boxplot(popDensity ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "popDensity", side =2, line =2, cex =  0.7)
par(par2)

par3<- par(mfrow=c(3,3), mar =c(3,3,3,3))
boxplot(pctForeignBorn ~ medIncomeNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "medIncome", side =1, line =2, cex=0.7)
mtext(text = "pctForeignBorn", side =2, line =2, cex =  0.7)
par(par3)



barplot(prop.table(table(pctEmployNA)), col = c("red", "light blue"), main = "Missing pctEmploy values", xlab = "pctEmploy values", ylab = "Proportion of observations")
mosaicplot(table(State, pctEmployNA), cex.axis = .4, col = c("red", "light blue"), main = "Missing pctEmploy values")
mosaicplot(table(region, pctEmployNA), col = c("red", "light blue"), main = "Missing pctEmploy values")


para<- par(mfrow=c(3,3), mar =c(3,3,3,3))
boxplot(pctUrban~pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=.7)
mtext(text = "pctUrban", side =2, line =2, cex =  .7)
boxplot(pctWdiv ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctWdiv", side =2, line =2, cex =  0.7)
boxplot(pctLowEdu ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctLowEdu", side =2, line =2, cex =  0.7)
boxplot(pctNotHSgrad ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctNotHSgrad", side =2, line =2, cex =  0.7)
boxplot(pctCollGrad ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctCollGrad", side =2, line =2, cex =  0.7)
boxplot(pctUnemploy ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctUnemploy", side =2, line =2, cex =  0.7)
boxplot(medIncome ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "medIncome", side =2, line =2, cex =  0.7)
boxplot(pctKids2Par ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctKids2Par", side =2, line =2, cex =  0.7)
boxplot(pctKidsBornNevrMarr ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctKidsBornNevrMarr", side =2, line =2, cex =  0.7)
par(para)

parb<- par(mfrow=c(3,3), mar =c(3,3,3,3))
boxplot(pctHousOccup ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctHouseOccup", side =2, line =2, cex =  0.7)
boxplot(pctHousOwnerOccup ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctHouseOwnerOccup", side =2, line =2, cex =  0.7)
boxplot(pctVacantBoarded ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctVacantBoarded", side =2, line =2, cex =  0.7)
boxplot(pctVacant6up ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.6)
mtext(text = "pctVacant6up", side =2, line =2, cex =  0.6)
boxplot(ownHousMed ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "ownHousMed", side =2, line =2, cex =  0.7)
boxplot(ownHousQrange ~ pctEmployNA, col=c("red", "light blue"))
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "ownHousQrange", side =2, line =2, cex =  0.7)
boxplot(rentMed ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "rentMed", side =2, line =2, cex =  0.7)
boxplot(rentQrange ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "rentQrange", side =2, line =2, cex =  0.7)
boxplot(popDensity ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "popDensity", side =2, line =2, cex =  0.7)
par(parb)

parc<- par(mfrow=c(3,3), mar =c(3,3,3,3))
boxplot(pctForeignBorn ~ pctEmployNA, col=c("red", "light blue"), xlab = "", ylab="")
mtext(text = "pctEmploy", side =1, line =2, cex=0.7)
mtext(text = "pctForeignBorn", side =2, line =2, cex =  0.7)
par(parc)
     